package scaffold

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/shubhamoys/forgego/internal/pkg/constants"
	"github.com/shubhamoys/forgego/internal/prompts"
	"github.com/shubhamoys/forgego/internal/utils"
)

func ScaffoldProject(config *prompts.ProjectConfig) error {
	// Create project directory
	projectDir := config.ProjectName
	if err := utils.CreateDir(projectDir); err != nil {
		return err
	}

	// Generate folder structure based on project type
	switch config.ProjectType {
	case constants.ProjectTypeAPI:
		if err := scaffoldAPI(projectDir, config); err != nil {
			return err
		}
	case constants.ProjectTypeCLI:
		if err := scaffoldCLI(projectDir, config); err != nil {
			return err
		}
	case constants.ProjectTypeLibrary:
		if err := scaffoldLibrary(projectDir, config); err != nil {
			return err
		}
	default:
		return fmt.Errorf("unsupported project type: %s", config.ProjectType)
	}

	// Write go.mod
	goModContent := fmt.Sprintf(`module %s

go 1.23

require (
	github.com/gorilla/mux v1.8.1
	go.mongodb.org/mongo-driver v1.16.0
	github.com/joho/godotenv v1.5.1
)
`, config.PackageName)
	if err := utils.WriteFile(filepath.Join(projectDir, "go.mod"), goModContent); err != nil {
		return err
	}

	// Write .gitignore
	gitignoreContent := `*.exe
*.log
vendor/
.env
`
	if err := utils.WriteFile(filepath.Join(projectDir, ".gitignore"), gitignoreContent); err != nil {
		return err
	}

	// Write README.md
	readmeContent := fmt.Sprintf(`# %s

A %s project generated by ForgeGo.

## Setup
1. Install dependencies: `+"`go mod tidy`"+`
2. Run the API: `+"`go run ./cmd/%s`"+`
3. Access at `+"`http://localhost:8080`"+`
`, config.ProjectName, config.ProjectType, config.ProjectName)
	if err := utils.WriteFile(filepath.Join(projectDir, "README.md"), readmeContent); err != nil {
		return err
	}

	// Initialize Git repository if requested
	if config.InitGit {
		if err := utils.InitGit(projectDir); err != nil {
			return err
		}
	}

	return nil
}

func scaffoldAPI(projectDir string, config *prompts.ProjectConfig) error {
	// Create API-specific structure
	dirs := []string{
		filepath.Join(projectDir, "cmd", config.ProjectName),
		filepath.Join(projectDir, "internal", "api"),
		filepath.Join(projectDir, "internal", "handlers"),
		filepath.Join(projectDir, "internal", "models"),
		filepath.Join(projectDir, "internal", "config"),
	}
	for _, dir := range dirs {
		if err := utils.CreateDir(dir); err != nil {
			return err
		}
	}

	// Write main.go
	mainContent := fmt.Sprintf(`package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"github.com/gorilla/mux"
	"%s/internal/config"
	"%s/internal/handlers"
)

func main() {
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("Failed to load config: %%v", err)
	}

	r := mux.NewRouter()
	r.HandleFunc("/api/health", handlers.HealthCheck).Methods("GET")

	addr := fmt.Sprintf(":%s", cfg.Port)
	log.Printf("Starting server on %%s", addr)
	log.Fatal(http.ListenAndServe(addr, r))
}
`, config.PackageName, config.PackageName)
	if err := utils.WriteFile(filepath.Join(projectDir, "cmd", config.ProjectName, "main.go"), mainContent); err != nil {
		return err
	}

	// Write handlers/health.go
	healthContent := `package handlers

import (
	"fmt"
	"net/http"
)

func HealthCheck(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "API is healthy")
}
`
	if err := utils.WriteFile(filepath.Join(projectDir, "internal", "handlers", "health.go"), healthContent); err != nil {
		return err
	}

	// Write config/config.go
	configContent := fmt.Sprintf(`package config

import (
	"github.com/joho/godotenv"
)

type Config struct {
	Port        string
	MongoDBURI  string
}

func Load() (*Config, error) {
	err := godotenv.Load()
	if err != nil {
		return nil, err
	}

	return &Config{
		Port:       "8080",
		MongoDBURI: "mongodb://localhost:27017",
	}, nil
}
`)
	if err := utils.WriteFile(filepath.Join(projectDir, "internal", "config", "config.go"), configContent); err != nil {
		return err
	}

	// Write .env
	envContent := `PORT=8080
MONGODB_URI=mongodb://localhost:27017
`
	if err := utils.WriteFile(filepath.Join(projectDir, ".env"), envContent); err != nil {
		return err
	}

	// Write Dockerfile if database is selected
	if config.Database != constants.DatabaseNone {
		dockerfileContent := fmt.Sprintf(`FROM golang:1.23
WORKDIR /app
COPY go.mod go.sum .
RUN go mod download
COPY . .
RUN go build -o %s ./cmd/%s
EXPOSE 8080
CMD ["./%s"]
`, config.ProjectName, config.ProjectName, config.ProjectName)
		if err := utils.WriteFile(filepath.Join(projectDir, "Dockerfile"), dockerfileContent); err != nil {
			return err
		}
	}

	// Write docker-compose.yml for MongoDB
	if config.Database == constants.DatabaseMongoDB {
		dockerComposeContent := `version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
`
		if err := utils.WriteFile(filepath.Join(projectDir, "docker-compose.yml"), dockerComposeContent); err != nil {
			return err
		}
	}

	return nil
}

func scaffoldCLI(projectDir string, config *prompts.ProjectConfig) error {
	// Create CLI-specific structure: cmd/, main.go
	if err := utils.CreateDir(filepath.Join(projectDir, "cmd", config.ProjectName)); err != nil {
		return err
	}

	// Write main.go
	mainContent := fmt.Sprintf(`package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func main() {
	var rootCmd = &cobra.Command{
		Use:   "%s",
		Short: "%s is a CLI tool",
	}
	if err := rootCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
`, config.ProjectName, config.ProjectName)
	if err := utils.WriteFile(filepath.Join(projectDir, "cmd", config.ProjectName, "main.go"), mainContent); err != nil {
		return err
	}

	return nil
}

func scaffoldLibrary(projectDir string, config *prompts.ProjectConfig) error {
	// Write main library file
	libContent := fmt.Sprintf(`package %s

// Add your library code here
`, strings.ReplaceAll(config.ProjectName, "-", "_"))
	if err := utils.WriteFile(filepath.Join(projectDir, fmt.Sprintf("%s.go", config.ProjectName)), libContent); err != nil {
		return err
	}

	return nil
}
